const PDFDocument = require('pdfkit');

const generateReport = (session, items, messType, res) => {
    const doc = new PDFDocument({ margin: 50 });

    // Stream to response
    doc.pipe(res);

    // -- Header --
    doc.fontSize(20).text('Hostel Menu Selection Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Session: ${session.title}`, { align: 'center' });
    doc.fontSize(12).text(
        `(${new Date(session.start_date).toLocaleDateString()} - ${new Date(session.end_date).toLocaleDateString()})`,
        { align: 'center' }
    );
    doc.moveDown();

    doc.rect(50, doc.y, 500, 30).fill('#4f46e5');
    doc.fillColor('white').fontSize(16).text(`${messType.toUpperCase()} MESS`, 50, doc.y - 23, { align: 'center', width: 500 });
    doc.fillColor('black');
    doc.moveDown(2);

    // -- Content --
    if (!items || items.length === 0) {
        doc.fontSize(12).text('No menu items found for this session/mess type.', { align: 'center' });
    } else {
        // Group items by Date
        const groupedByDate = items.reduce((acc, item) => {
            const date = item.date_served;
            if (!acc[date]) acc[date] = [];
            acc[date].push(item);
            return acc;
        }, {});

        Object.keys(groupedByDate).sort().forEach(date => {
            // Date Header
            const dateStr = new Date(date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

            doc.fontSize(14).font('Helvetica-Bold').text(dateStr);
            doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
            doc.moveDown(0.5);

            // Table Header for this date
            let y = doc.y;
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#555');
            doc.text('MEAL', 50, y);
            doc.text('ITEM', 130, y);
            doc.text('DESCRIPTION', 300, y);
            doc.text('VOTES', 500, y);
            doc.moveDown(0.5);
            doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#eee').stroke();
            doc.moveDown(0.5);
            doc.fillColor('black').font('Helvetica');

            // Sort items by meal order (breakfast, lunch, snacks, dinner)
            const mealOrder = { breakfast: 1, lunch: 2, snacks: 3, dinner: 4 };
            const dailyItems = groupedByDate[date].sort((a, b) => (mealOrder[a.meal_type] || 99) - (mealOrder[b.meal_type] || 99));

            dailyItems.forEach(item => {
                const votes = item.votes && item.votes[0] ? item.votes[0].count : 0;

                y = doc.y;

                // Meal Type
                doc.fontSize(10).text(item.meal_type.toUpperCase(), 50, y, { width: 70 });

                // Item Name
                doc.font('Helvetica-Bold').text(item.name, 130, y, { width: 160 });

                // Votes (Right aligned in its column)
                doc.font('Helvetica-Bold').fillColor(votes > 0 ? '#4f46e5' : '#aaa')
                    .text(votes.toString(), 500, y, { width: 50, align: 'left' });
                doc.fillColor('black');

                // Description (Multi-line possibility)
                doc.font('Helvetica').fontSize(9).text(item.description || '-', 300, y, { width: 190 });

                doc.moveDown(1);
            });

            doc.moveDown(1.5);
        });
    }

    // Footer
    const bottom = doc.page.height - 50;
    doc.fontSize(10).text('Generated by Hostel Menu System', 50, bottom, { align: 'center', width: 500 });

    doc.end();
};

module.exports = { generateReport };
